# Generated by Django 4.2.16 on 2024-11-10 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="nome",
            field=models.CharField(default="nulo", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="departamento",
            name="responsavelId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="departamento",
            name="tipoEntidade",
            field=models.CharField(default="A", max_length=256),
            preserve_default=False,
        ),
    ]
