# Generated by Django 4.2.16 on 2024-11-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_departamento_nome_departamento_responsavelid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="responsavelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsavel",
            ),
        ),
    ]
