# Generated by Django 5.1.3 on 2024-11-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_departamento_responsavelid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subordinacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataSubordinacao", models.DateTimeField(auto_now_add=True)),
                ("Observacao", models.TextField(blank=True, null=True)),
                (
                    "IdDepartamentoA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamentos_superiores",
                        to="core.departamento",
                    ),
                ),
                (
                    "IdDepartamentoB",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamentos_subordinados",
                        to="core.departamento",
                    ),
                ),
            ],
        ),
    ]
