# Generated by Django 5.1.3 on 2024-11-22 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_despesa_elemento_tipogasto_verba_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="responsabilidade",
            name="unique_user_departamento_responsabilidade",
        ),
        migrations.RenameField(
            model_name="responsabilidade",
            old_name="dataCriacao",
            new_name="data_criacao",
        ),
        migrations.RenameField(
            model_name="responsabilidade",
            old_name="user",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="subordinacao",
            old_name="dataSubordinacao",
            new_name="data_subordinacao",
        ),
        migrations.RenameField(
            model_name="subordinacao",
            old_name="departamentoB",
            new_name="subordinado",
        ),
        migrations.RenameField(
            model_name="subordinacao",
            old_name="departamentoA",
            new_name="superior",
        ),
        migrations.AddField(
            model_name="verba",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="responsabilidade",
            constraint=models.UniqueConstraint(
                fields=("usuario", "departamento"),
                name="unique_usuario_departamento_responsabilidade",
            ),
        ),
    ]
