# Generated by Django 5.1.3 on 2024-11-23 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_remove_responsabilidade_unique_user_departamento_responsabilidade_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="responsabilidade",
            name="unique_usuario_departamento_responsabilidade",
        ),
        migrations.RemoveField(
            model_name="verba",
            name="dataAtribuicao",
        ),
        migrations.AddConstraint(
            model_name="responsabilidade",
            constraint=models.UniqueConstraint(
                fields=("usuario", "departamento"), name="unique_user_dep_resp"
            ),
        ),
    ]
