# Generated by Django 5.1.3 on 2024-11-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0010_remove_responsabilidade_unique_usuario_departamento_responsabilidade_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementoTipoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_gasto",
                        to="core.elemento",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementos",
                        to="core.tipogasto",
                    ),
                ),
            ],
            options={
                "unique_together": {("elemento", "tipo_gasto")},
            },
        ),
    ]
