# Generated by Django 5.1.3 on 2025-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_elementotipogasto"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subordinacao",
            constraint=models.UniqueConstraint(
                fields=("superior", "subordinado"), name="unique_subordinacao"
            ),
        ),
    ]
