# Generated by Django 5.1.3 on 2025-04-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_elementotipogasto"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeiNorma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("numero", models.CharField(max_length=50)),
                ("data_publicacao", models.DateField()),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="leis_normas/"),
                ),
            ],
        ),
    ]
