# Generated by Django 5.1.3 on 2025-04-22 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_subordinacao_unique_subordinacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="verba",
            name="ano",
            field=models.IntegerField(db_index=True, verbose_name="Ano"),
        ),
        migrations.AddIndex(
            model_name="verba",
            index=models.Index(
                fields=["departamento", "ano"], name="core_verba_departa_0dfc18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verba",
            index=models.Index(fields=["ano"], name="core_verba_ano_53b9d1_idx"),
        ),
    ]
