# Generated by Django 5.1.3 on 2025-05-05 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_verba_ano_verba_core_verba_departa_0dfc18_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="responsavelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsavel",
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="despesas_departamento",
                to="core.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="elemento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="despesas_elemento",
                to="core.elemento",
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="tipoGasto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="despesas_tipoGasto",
                to="core.tipogasto",
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="despesas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subordinacao",
            name="subordinado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departamentos_subordinados",
                to="core.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="subordinacao",
            name="superior",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departamentos_superiores",
                to="core.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="verba",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="verbas_estipuladas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuário que atribuiu",
            ),
        ),
    ]
