# Generated by Django 5.1.3 on 2025-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_departamento_responsavelid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="tipoEntidade",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
