# Generated by Django 4.2.16 on 2024-11-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.CharField(default="Administrador", max_length=256),
            preserve_default=False,
        ),
    ]
