# Generated by Django 4.2.16 on 2024-11-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="roles",
            new_name="grupo",
        ),
    ]
