# Generated by Django 4.2.13 on 2024-11-06 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TipoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="departamento",
            name="IdUserResp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="departamento",
            name="Nome",
            field=models.CharField(default="Departamento de Lazer", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="departamento",
            name="TipoEntidade",
            field=models.CharField(default="A", max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Verba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataAtribuicao", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.TextField()),
                (
                    "IdDepartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verbas",
                        to="core.departamento",
                    ),
                ),
                (
                    "IdUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verbas_atribuidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubordinadoA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataSubordinacao", models.DateTimeField(auto_now_add=True)),
                ("Observacao", models.TextField(blank=True, null=True)),
                (
                    "IdDepartamentoA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamentos_superiores",
                        to="core.departamento",
                    ),
                ),
                (
                    "IdDepartamentoB",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamentos_subordinados",
                        to="core.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponsavelDepartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataCriacao", models.DateTimeField(auto_now_add=True)),
                ("Observacao", models.TextField(blank=True, null=True)),
                (
                    "IdDepartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsaveis",
                        to="core.departamento",
                    ),
                ),
                (
                    "IdUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Justificativa", models.TextField()),
                (
                    "IdDepartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="core.departamento",
                    ),
                ),
                (
                    "IdElemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="core.elemento",
                    ),
                ),
                (
                    "IdTipoGasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="core.tipogasto",
                    ),
                ),
                (
                    "IdUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
